### PR TITLE
Remove concmath to get vector math fonts

### PR DESCRIPTION
**Pull request by wilson-nunn**

### CODE REVIEW

**Comment by andeElliott** [comment]
Completely agree, removing this package, make the equations look nicer and are also vector so presenting at an unknown resolution is less stressful :-)

**Comment by martintoreilly** [comment]
@wilson-nunn So sorry I lost track of this PR over the summer. Can you or @andeElliott provide a LaTeX snippet with some typeset equations so I can test the change locally?

@wilson-nunn Please could you also update the PR name and description to be a bit more descriptive of the effect of the change, so our future selves stand a chance of inferring what the change is without inspecting the commits?

**Comment by martintoreilly** [comment]
@wilson-nunn Here's a starter for 10 on the title - is it reflective of the change? If there's more useful info about why the change is useful, then please add to the description.

Title: Remove concmath to get vector math fonts

**Comment by andeElliott** [comment]
I will leave the title to @wilson-nunn however that looks fine to me.

You should be able to see it on any equation if you zoom (the style is also different if that helps), so for example:
\begin{equation}
y=mx+c
\end{equation}

**Pull request merged**
