### PR TITLE
Set color of font in toc

### PR DESCRIPTION
**Pull request by GjjvdBurg**
Fixes font color for the table of contents

### CODE REVIEW

**Comment by martintoreilly** [comment]
@GjjvdBurg If you haven't already, please could you add a TOC to the example skeleton, rebuild and commit the PDF as a demonstration of the style in action?

**Comment by GjjvdBurg** [comment]
@martintoreilly No problem! Note that without the fix the font in the toc has a blue color, which is particularly hard to see with the dark theme.

**Comment by martintoreilly** [comment]
The TOC text still looks blue in the committed PDF.

**Comment by GjjvdBurg** [comment]
Apologies, fixed now.

**Pull request merged**
